#!/bin/bash

# Defaults settings
CONFIG_DIR="$HOME/.config/cli-bookmarker/"
BM_LAUNCHER=xdg-open #default application to launch URLs
BM_EDITOR=${EDITOR} # change editor used with bm -e
BM_DB="$HOME/bookmarks" # where the bookmarks are stored
CONFIG_FILE="$HOME/.config/cli-bookmarker/bmrc"

#Helper Functions

# join string
join_by() { join_by_d=${1-} join_by_f=${2-}; if shift 2; then printf %s "$join_by_f" "${@/#/$join_by_d}"; fi; }

# trim string
trim() { 
    sed -e 's/^[[:space:]]*//'
}
# beautiful print of bookmarks file
bm_print() { 
    bm_print_f=$1
    # cat -n $bm_print_f | column -t -s $'\t'
    cat -n $bm_print_f 
}

# output configuration file
output_config() {
cat <<EOF
###################################################################
# General Configuration
#------------------------------------------------------------------
# 
# Must be written bellow [general]
#
# bmfile <file> is the default bookmark file
# editor <editor> is the default text editor
# browser <browser> defines the default browser
#
# example:
#
# [general]
# bmfile $HOME/bookmarks
# editor vim
# browser firefox
####################################################################

#####################################################################
# URL Configuration
#--------------------------------------------------------------------
#
# Must be written bellow [urls]
#
# You can assign specific URLs to specific software
# the url selected with bm -o will be matched with the urls bellow
# and the software from the last match will be chosen 
# [url pattern] <software>
#
# example:
# 
# [urls]
#
# youtube.com/watch mpv
# gemini:// amfora
# github.com firefox
######################################################################
EOF
}

output_version() {
cat <<EOF
cli-bookmarker 2.0
License GPLv3: GNU GPL version 3.
This is free software: you are free to change and redistribute it.

Written by Paulo Neto
<https://github.com/paulonetodev/cli-bookmarker/>
EOF
}

output_help() {
cat <<EOF

cli-bookmarker: Save and launch bookmarks

Usage:

    bm [url] [description]? [tag...]?
    bm [option]
    bm [option] [tag]
    bm [option] [id...]
    bm [option] [url]

Options:

    -l, list all the bookmarks
    -r, remove bookmark with the specified id, or search with fzf if not
    -o, open bookmark if id is specified, open URL if a url is specified or, search with fzf if no argument was given
    -e, edit with default text editor
    -t, if tag is provided, fuzzy search of entries with an especific tag. If tag is not provided, list all tags
    -h, --help show help
    -v, --version show version
        --create-config, create a configuration file: $HOME/.config/cli-bookmarker/bmrc

Examples

    Create bookmark. Description and tags are optional
    bm https://wiki.archlinux.org 
    bm https://wiki.archlinux.org "arch wiki"
    bm https://wiki.archlinux.org "arch wiki" tag1 tag2

    list bookmarks, it's possible to filter by tags
    bm -l
    bm -l classical-music

    remove entries. If no argument is given a fuzzy search prompt will open
    multiple entries can be selected with tab
    bm -r 
    bm -r 2 3

    launch any URL or bookmark entry.
    If no argument is provided, a fuzzy search prompt will open.
    bm -o www.linux.org
    bm -o 2
    bm -o

    search bookmark with specific tag
    bm -t linux

    List all tags
    bm -t

    edit bookmark file
    bm -e

More help at <https://github.com/paulonetodev/cli-bookmarker>
EOF
}

# should receive the URL that will be launched and the URLS array from the configuration file
# it returns the launcher associated with the last URL that matches with the URLS array
get_launcher() {
    # URL we want to launch
    GET_LAUNCHER_LAUNCH_URL=$1
    # URLs associated with diferent launchers in the config file
    GET_LAUNCHER_URLS_ARR_N=$2[@]
    GET_LAUNCHER_URLS_ARR=("${!GET_LAUNCHER_URLS_ARR_N}")
    #default launcher if no match occurs
    GET_LAUNCHER_LAUNCHER=$BM_LAUNCHER

    #check if there's a match in the URLS array
    for i in "${GET_LAUNCHER_URLS_ARR[@]}"
    do
        GET_LAUNCHER_CURRENT_URL=`echo $i | awk '{print $1}'`
        GET_LAUNCHER_CURRENT_APP=`echo $i | awk '{print $2}'`
        if grep -q "$GET_LAUNCHER_CURRENT_URL" <<< "$GET_LAUNCHER_LAUNCH_URL"; then
            GET_LAUNCHER_LAUNCHER=$GET_LAUNCHER_CURRENT_APP
        fi
    done
    
    echo $GET_LAUNCHER_LAUNCHER
}

# Parsing the configuration file
# These arrays represent the lines of each section of bmrc
GENERAL=()
URLS=()

if test -f "$CONFIG_FILE"; then 
  #Config file exists: Parse it and assign new defaults
  CURR="none";
  while IFS= read -r line
    do
      line=`echo $line | trim | envsubst`
      if [ "$line" = "[general]" ]; then CURR="general"
      elif [ "$line" = "[urls]" ]; then CURR="urls"
      else
        case $CURR in
            "general") GENERAL+=("$line") ;;
            "urls") URLS+=("$line") ;;
            *) ;;
        esac
      fi
   done <<EOF
$(sed 's/#.*$//;/^$/d' $CONFIG_FILE)
EOF
    # echo ${GENERAL[@]}
    # echo ${URLS[@]}

    # assign new config defaults
    for i in "${GENERAL[@]}"
    do
        gc=`echo $i | awk '{print $1}'`
        gs=`echo $i | awk '{print $2}'`
        case $gc in
            "bmfile")
                BM_DB=$gs
            ;;
            "editor")
                BM_EDITOR=$gs
            ;;
            "browser")
                BM_LAUNCHER=$gs
            ;;
            *)
                echo "invalid configuration"
            ;;
        esac
    done;
else
    echo "Configuration file not found. You can create one with bm --create-config"
fi

#Main logic
case $1 in
    "-l") 
        #list bookmarks
        if [ -z "$2" ]; then 
            # no tag was given: list all
            # cat -n ${BM_DB} | awk '{ $3 = "\t" $3; print}' | column -t -s $'\t'
            bm_print ${BM_DB}
        else
            # tag was given: list only entries that match
             bm_print ${BM_DB} | grep "\[.*$2.*\]"
        fi   
        ;;
    "-r") 
        ARR=()
        #remove bookmark if id is provided
        if [ ! -z "$2" ]; then        
            # add lines that will be deleted to an array           
            while (( "$#-1" )); do
                ARR+=($2d)
                shift 
            done
        else
            # user can select multiple entries. This returns the ids list that will be used by sed, example: [3d 5d 7d]
            # ARR=(`cat -n ./bookmarks | fzf -m | awk '{print $1"d"}' | xargs echo`)
            ARR=(`bm_print ${BM_DB} | fzf -m --delimiter=$'\t' --preview-window right:45%:wrap --preview='printf "Title: %b\n\nTags: %b\n\nUrl: %b\n\n" {2} {3} {4}' | awk '{print $1"d"}' | xargs echo`)
        fi
        #delete the lines
        if [ ${#ARR[@]} -ne "0" ]; then
            sed -i.bak `join_by ";" $(printf '%s\n' "${ARR[*]}")` ${BM_DB} 
        fi       
        ;;
    "-o"|"") 
        # bm -o and bm open search prompt
        # bm -o <url> launch a website
        # bm -o <id> launch website from bookmark
        #open bookmark or URL
        if [ -z "$2" ]; then 
            # id not provided: open search prompt
            LINE=`bm_print ${BM_DB} | fzf --delimiter=$'\t' --preview-window right:45%:wrap --preview='printf "Title: %b\n\nTags: %b\n\nUrl: %b\n\n" {2} {3} {4}'`             
            if [ ! -z "$LINE" ]; then 
                # URL=`echo $LINE | awk '{print $2}'`
                URL=`echo $LINE | awk '{print $NF}'`
            fi
        else
            #argument was provided
            re='^[0-9]+$'
            if ! [[ $2 =~ $re ]] ; then
                # not a number, assume it's a url
                URL=$2
            else 
                #it's a number: just take the URL from the line number provided
                URL=`sed -n $2p ${BM_DB} | awk '{print $NF}'`
            fi

            
        fi
        [ ! -z "$URL" ] && $(get_launcher $URL "URLS") $URL;
        ;;
    "-t")
        # open with tag search
        if [ ! -z "$2" ]; then 
            # tag is provided, open search
            LINE=`bm_print ${BM_DB} | grep "\[.*$2.*]" | fzf --delimiter=$'\t' --preview-window right:45%:wrap --preview='printf "Title: %b\n\nTags: %b\n\nUrl: %b\n\n" {2} {3} {4}'`
            if [ ! -z "$LINE" ]; then 
                # open the selected url
                URL=`echo $LINE | awk '{print $NF}'`
                [ ! -z "$URL" ] && $(get_launcher $URL "URLS") $URL;
            fi
        else
            # tag not provided, list all tags
            all_tags=`grep -oP '\[\K[^]]*' ${BM_DB}`
            echo $all_tags | tr ' ' '\n' | sort -u
        fi
        ;;
    "-e")
        #edit with text editor
        ${BM_EDITOR} ${BM_DB}
        ;;
    "-h"|"--help")
        output_help
        ;;
    "-v"|"--version")
        output_version
        ;;
    "--create-config")
        [ ! -d "$CONFIG_DIR" ] && mkdir -p "$CONFIG_DIR"
        output_config > "$CONFIG_DIR/bmrc"
        echo "Configuration file created: $HOME/.config/cli-bookmarker/bmrc"
        ;;    
    *)
        if [[ ${1:0:1} == "-" ]]; then
            echo "invalid command. Use bm -h for help" >&2; exit 1
        else
            #bm [url] [description]? [tags]? should add a bookmark
            SITE=$1
            TAGS=()
            TAGSSTR=""
            DESCR=""

            # check if there's description
            if [ ! -z "$2" ]; then
                DESCR="$2"
                #check if there's tags
                if [ ! -z "$3" ]; then 
                    while (( "$#" )); do
                        TAGS+=($3)
                        shift 
                    done
                    TAGSSTR=`printf '[%s] ' "${TAGS[*]}"`
                fi   

            fi
            echo -e "$DESCR\t$TAGSSTR\t$SITE" >> ${BM_DB}   
        fi
        ;;
esac
